# Generated by Django 2.1.5 on 2019-01-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('mother_alphabet', models.CharField(max_length=20)),
            ],
        ),
    ]
