# Generated by Django 2.1.5 on 2019-01-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_text',
            field=models.TextField(default=''),
        ),
    ]
