# Generated by Django 2.1.5 on 2019-01-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lesson_lesson_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='language',
            field=models.CharField(max_length=50),
        ),
    ]
