# Generated by Django 2.1.5 on 2019-01-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190115_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='text_color',
            field=models.CharField(default='text-white', max_length=20),
        ),
    ]
