# Generated by Django 2.1.5 on 2019-01-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_language_text_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.IntegerField()),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
