# Generated by Django 2.1.5 on 2019-01-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190121_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
