# Generated by Django 2.1.5 on 2019-01-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100)),
                ('lesson', models.IntegerField()),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
    ]
