# Generated by Django 2.1.5 on 2019-01-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_question_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonitauruser',
            name='lessons',
            field=models.ManyToManyField(to='users.Lesson'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
    ]
